## Regularization test simulation

In [1]:
%matplotlib inline

In [3]:
import os, sys
os.chdir("/Users/njchiang/GitHub/tikhonov")

In [5]:
import numpy as np
from tikhonov import TikhonovRegression as tik
from sklearn.linear_model import Ridge, LinearRegression

In [20]:
Sigma = np.array([[1, 0, .5], [0, 1, .5], [.5, .5, 1]])
n = 3

In [21]:

nf = Sigma.shape[0]
x = np.random.rand(n, nf)
b = np.random.multivariate_normal(np.zeros(nf), Sigma)

In [22]:
x = x - x.mean(0)
y = np.dot(x, b) + np.random.randn(n)/10

In [23]:
ols = LinearRegression(fit_intercept=False)
ridge = Ridge(fit_intercept=False)

In [24]:
o = ols.fit(x, y).coef_
t = ridge.fit(x, y).coef_
te = tik.analytic_tikhonov(x, y, 1, np.eye(nf))
ta = tik.analytic_tikhonov(x, y, 1, Sigma)

In [25]:
gamma = tik.find_gamma(Sigma)


In [26]:

x_new, y_new = tik.to_standard_form(x, y, gamma)
ta_est_standard = ridge.fit(x_new, y_new).coef_
ta_est = tik.to_general_form(ta_est_standard, x, y, gamma)

In [27]:
# verify that ta_est and ta are the sample
# verify that te and t are the sample
# verify that ta and te are close

In [28]:
ta_est

array([ 0.309255  , -0.05205724,  0.21173504])

In [29]:
t

array([ 0.23789321, -0.13829921,  0.17455841])

In [30]:
ta

array([ 0.309255  , -0.05205724,  0.21173504])

In [31]:
o

array([ 0.76973833, -0.72586685,  0.59113317])

In [32]:
b

array([ 0.20755041, -0.51400261,  1.58685615])